### ISSUE TITLE
Upgrade to Protobuf 4.x

### ISSUE THREAD

**Issue by ee08b397** [blackrock/protoc-jar-maven-plugin#27]
**Is your feature request related to a problem? Please describe.**
I would like to use the latest released version of Protobuf (4.27.0). Find the latest version from https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java. 

**Describe the solution you'd like**
Update Protobuf dependency and make it work with the new version. 
- protoc-jar-maven-plugin supports v2 and v3. See if protoc-jar-maven-plugin can support v4 in the same code. 
- If not, support in a separate branch and lay out the breaking changes between v3 and v4. 

**Describe alternatives you've considered**
N/A. Don't upgrade just yet :)

**Additional context**
Refer to gPRC Protobuf v4 upgrade and share insights or roadblocks https://github.com/grpc/grpc-java/issues/11015

**Comment by ee08b397** [comment]
Having this error with protobuf
```
<dependency>
	<groupId>com.google.protobuf</groupId>
	<artifactId>protobuf-java</artifactId>
	<version>4.27.2</version>
</dependency>
```
From `mvn test`
```
[ERROR] io.github.blackrock.protocjar.ProtocTest.testStdTypes -- Time elapsed: 0.277 s <<< ERROR!
java.io.FileNotFoundException: Unsupported platform: protoc-2.6.1-osx-aarch_64.exe
	at io.github.blackrock.protocjar.Protoc.extractProtoc(Protoc.java:223)
	at io.github.blackrock.protocjar.Protoc.extractProtoc(Protoc.java:184)
	at io.github.blackrock.protocjar.Protoc.runProtoc(Protoc.java:68)
	at io.github.blackrock.protocjar.Protoc.runProtoc(Protoc.java:55)
	at io.github.blackrock.protocjar.ProtocTest.testStdTypes(ProtocTest.java:82)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MavenUtilTest.testParseSnapshotExeName:60 expected: <protoc-2.4.1-20180823.052533-7-osx-x86_64.exe> but was: <null>
[ERROR] Errors: 
[ERROR]   ProtocTest.testRunProtocBasic:36 » FileNotFound Unsupported platform: protoc-2.4.1-osx-aarch_64.exe
[ERROR]   ProtocTest.testRunProtocCompile:99 » FileNotFound Unsupported platform: protoc-2.4.1-osx-aarch_64.exe
[ERROR]   ProtocTest.testRunProtocCompileShade:119 » FileNotFound Unsupported platform: protoc-2.4.1-osx-aarch_64.exe
[ERROR]   ProtocTest.testRunProtocDownloadArtifact:67 » FileNotFound https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.4.0/protoc-3.4.0-osx-aarch_64.exe
[ERROR]   ProtocTest.testStdTypes:82 » FileNotFound Unsupported platform: protoc-2.6.1-osx-aarch_64.exe
[INFO] 
[ERROR] Tests run: 9, Failures: 1, Errors: 5, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for protoc-jar-maven-plugin 2.0-SNAPSHOT:
[INFO] 
[INFO] protoc-jar-maven-plugin ............................ SUCCESS [  0.001 s]
[INFO] protoc-jar ......................................... FAILURE [  2.410 s]
[INFO] maven-plugin ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```
